# Generated by Django 3.1.6 on 2021-03-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userHobby',
        ),
    ]
