# Generated by Django 3.1.6 on 2021-03-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hobbylist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hobbylist',
        ),
        migrations.DeleteModel(
            name='HobbyList',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
